# Generated by Django 5.1.6 on 2025-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_product_stock_debtrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5, help_text='Minimum stock level before alert is triggered'),
        ),
    ]
